---
# tasks file for javarole
    - name: get url
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: install packages
      ansible.builtin.command: sudo dpkg -i /tmp/packages-microsoft-prod.deb
    - name: Update cache
      ansible.builtin.apt:
        update_cache: yes
    - name: install dotnet runtime
      ansible.builtin.apt:
        name: apt-transport-https
        state: present
    - name: install dotnet runtime
      ansible.builtin.apt:
        name: aspnetcore-runtime-7.0
        state: present
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: systemctl restart
      ansible.builtin.systemd:
        name: nginx
        state: started
    - name: remove file
      ansible.builtin.file:
        path: /etc/nginx/sites-available/default
        state: absent
    - name: Copy file
      ansible.builtin.copy:
        src: default
        dest: /etc/nginx/sites-available/default
    - name: Create an directory
      ansible.builtin.file:
        path: /var/www/nopCommerce
        state: directory
    - name: get url
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
    - name: install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
    - name: Unarchive a file
      ansible.builtin.unarchive:
        src: /var/www/nopCommerce/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce/
        remote_src: yes
    - name: Create an directory
      ansible.builtin.file:
        path: /var/www/nopCommerce/bin
        state: directory
    - name: Create an directory
      ansible.builtin.file:
        path: /var/www/nopCommerce/logs
        state: directory
    - name: Change group ownership
      ansible.builtin.file:
        path: /var/www/nopCommerce/
        owner: www-data
        group: www-data
        recurse: yes
    - name: Copy service file
      ansible.builtin.copy:
        src: nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
        remote_src: yes
    - name: systemctl restart
      ansible.builtin.systemd:
        name: nopCommerce.service
        state: started
    - name: systemctl restart
      ansible.builtin.systemd:  
        name: nginx   
        state: restarted  